behaviors:
  Move_Along:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.9
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: true
        use_vail: false
        demo_path: D:\Unity_projects\Robotic_trainingAI\Demonstrations\cloningsimple_7.demo
    keep_checkpoints: 5
    max_steps: 6000000
    time_horizon: 64
    summary_freq: 60000
    behavioral_cloning: #pre-training
      demo_path: D:\Unity_projects\Robotic_trainingAI\Demonstrations\cloningsimple_7.demo
      steps: 700000
      strength: 0.1
      samples_per_update: 10240
      num_epoch: 3
      batch_size: 32
checkpoint_settings:
  run_id: test30
  initialize_from: null
  results_dir: results
